version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-wishlist
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: wishlist-db
    volumes:
      - ./data/db:/data/db

  app:
    build:
      context: .
    container_name: wishlist-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo-wishlist:27017/wishlist-db?authSource=admin
    depends_on:
      - mongodb